version: '2'
services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.104:9092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.104
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      JMX_PORT: 9999
    volumes:
      - /usr/local/docker-compose/kafka/kafka1:/kafka
    external_links: # 连接compose文件以外的container
      - zoo1
  kafka2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.104:9093
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.104
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      JMX_PORT: 9988
    volumes:
      - /usr/local/docker-compose/kafka/kafka2:/kafka
    external_links: # 连接compose文件以外的container
      - zoo1

  kafka3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.104:9094
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.104
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      JMX_PORT: 9977
    volumes:
      - /usr/local/docker-compose/kafka/kafka3
    external_links: # 连接compose文件以外的container
      - zoo1


  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: always
    container_name: kafa-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links: # 连接本compose文件创建的container
      - kafka1
      - kafka2
      - kafka3
    external_links: # 连接compose文件以外的container
      - zoo1
    environment:
      ZK_HOSTS: zoo1:2181
      KAFKA_BROKERS: kafka1:9092,kafka2:9093,kafka3:9094
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true

networks:
  default:
    external: # 使用已创建的网络
      name: zookeeper_network
