server:
  port: 8083
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/ #注册到刚才那台Eureka Server地址
spring:
  application:
    name: client-1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.100:3306/ys_znjx?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:Schema.sql
spring.datasource.initialization-mode: always